### PR TITLE
fix created_at in factories

### PR DESCRIPTION
**Pull request by cmrd-senya**

### CODE REVIEW

**Comment by SuperTux88** [comment]
Please don't create release-PRs, I'll create releases when needed. Also I don't want to cherry-pick commits for the releases, I always release the whole develop branch (except if it is something security-relevant). Because of that I didn't look at #23 in detail, and thought everything you need will be released if I release the develop branch. I didn't see that the PR contains changes that aren't in develop yet. So please create your changes as normal PRs.

Also: diaspora uses UTC in the database and also in federation. Where does it need local timezone?

**Comment by cmrd-senya** [comment]
You must have explained your point before. That's why I wanted a discussion. I was unsure about what you had on your mind. Just silently ignoring something you don't agree with is unproductive and impolite as long as I post requests for reason. I can't post changes without them being reviewed, but I didn't have a chance to review your changes when you made it. Otherwise I would notice something important lacks from the release.

I can drop the release commit, but I need a release to merge https://github.com/diaspora/diaspora/pull/6595. I also was going to propose to release a version 0.1.0 when we would have merge receive updates, because it makes more sense for semver and would mark some sort of important change.

It's not about timezones, it is about string format returned by different functions. Probably we don't need ```Time.zone.now``` then, but something else, but ```DateTime.now.utc``` returns a string in a format that doesn't match with the format produced by Diaspora

**Comment by cmrd-senya** [comment]
That's what I talk about

**Comment by SuperTux88** [comment]
I already said, that I wasn't really active in IRC the last few days, sorry for that. And sorry that I didn't see that #23 contained additional commits, I've only read the title and thought it is something like #15 but only with a few commits. So I thought if I release all commits from develop, everything is fine.

You're welcome to give feedback to my commits, if you want to review them.

I will release 0.1.0 if the gem is fully functional integrated in diaspora.

If it is only the string-format, maybe you can use `Time.now.utc` like in the entities as default?

**Comment by cmrd-senya** [comment]
Looks like it is ok with the default.

**Comment by cmrd-senya** [comment]
I think that fully functional gem integrated to Diaspora must be called 1.0.0 version according to semver. Semver says that 0.0.* versioning is not cool.

**Comment by SuperTux88** [comment]
using the default breaks the tests. but you can use the same as for default

semver doesn't make much sense at the current time of development. there are changes that need changes in diaspora in every release.

1.0.0 will be the version when all todos and cleanups are done.

**Comment by cmrd-senya** [comment]
Updated

**Comment by SuperTux88** [comment]
merged, thx. I'll release this today evening when I'm at home.

**Comment by cmrd-senya** [comment]
Great! Thanks for that!

**Pull request merged**
